# Scaffolding generated by Casein v5.0.1.0

module Casein
  class TicketsController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Tickets'
  		@tickets = Ticket.order(sort_order(:name)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View ticket'
      @ticket = Ticket.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new ticket'
    	@ticket = Ticket.new
    end

    def create
      @ticket = Ticket.new ticket_params
    
      if @ticket.save
        flash[:notice] = 'Ticket created'
        redirect_to casein_tickets_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new ticket'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update ticket'
      
      @ticket = Ticket.find params[:id]
    
      if @ticket.update_attributes ticket_params
        flash[:notice] = 'Ticket has been updated'
        redirect_to casein_tickets_path
      else
        flash.now[:warning] = 'There were problems when trying to update this ticket'
        render :action => :show
      end
    end
 
    def destroy
      @ticket = Ticket.find params[:id]

      @ticket.destroy
      flash[:notice] = 'Ticket has been deleted'
      redirect_to casein_tickets_path
    end
  
    private
      
      def ticket_params
        params.require(:ticket).permit(:name, :url)
      end

  end
end