# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 029c7aa9f40049846caec114b819a8f2030af106413657c50894b82c041d90df8cdd927d5e76ea3b08cb29ec718da29dabf78d4b80211ccaf5ec6f2d0f0fb621

test:
  secret_key_base: fd4812f7c8a17ce2895bcd8699228f8b898e27a774c6cadc5aa45e9c907dde778dad828309c3fec16cd4638e6ffcd4be0977b044994d314c2a86b16cacece77b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
